# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#    parameter_name: value

services:
#    csv.parser:
#        class: AppBundle\Service\CSVParser
#
#    record.validator:
#        class: AppBundle\Service\RecordValidator
#
#    db.processor:
#        class: AppBundle\Service\DBProcessor
#        arguments:
#            - '@doctrine.orm.entity_manager'

    filter:
        class: AppBundle\Service\FilterService

    converter:
        class: AppBundle\Service\ConverterService

    mapping:
        class: AppBundle\Service\MappingService

    workflow.organizer:
        class: AppBundle\Service\WorkflowOrganizer
        arguments:
            - '@filter'
            - '@converter'
            - '@mapping'
            - '@doctrine.orm.entity_manager'

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
